// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9iykD5qRrGRt8dPAcrB_CHPlrp3I4Mr8',
    appId: '1:1042695203771:web:ded61a2c1a871fee40f29e',
    messagingSenderId: '1042695203771',
    projectId: 'taskmaster-a103f',
    authDomain: 'taskmaster-a103f.firebaseapp.com',
    storageBucket: 'taskmaster-a103f.firebasestorage.app',
    measurementId: 'G-HXG612H5C3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzuMzfrcLVQbA1iJSi8PrK-OMW9pJdigQ',
    appId: '1:1042695203771:android:f0bee3910b7b63d240f29e',
    messagingSenderId: '1042695203771',
    projectId: 'taskmaster-a103f',
    storageBucket: 'taskmaster-a103f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9iykD5qRrGRt8dPAcrB_CHPlrp3I4Mr8',
    appId: '1:1042695203771:web:01506f36e5d0c86940f29e',
    messagingSenderId: '1042695203771',
    projectId: 'taskmaster-a103f',
    authDomain: 'taskmaster-a103f.firebaseapp.com',
    storageBucket: 'taskmaster-a103f.firebasestorage.app',
    measurementId: 'G-2GP9R5VQEW',
  );
}
